version: '3.9'
services:
  app:
    image: php:8.2-fpm
    container_name: laravel_app
    build: 
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - .:/var/www/html
      # - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    networks:
      - laravel_network
    # user: $USERID

  db:
    image: mysql:5.7
    container_name: laravel_db
    environment:
        MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        MYSQL_DATABASE: ${DB_DATABASE}
        MYSQL_HOST: ${DB_HOST}
        # MYSQL_USER: ${DB_USERNAME}
        MYSQL_PASSWORD: ${DB_PASSWORD}
    networks:
      - laravel_network
    ports:
      - "3307:3306"

  nginx:
    image: nginx:latest
    container_name: laravel_nginx
    ports:
      - "8081:8080"
    volumes:
      - ./docker/nginx/app.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/html
    depends_on:
      - app
    networks:
      - laravel_network

networks:
  laravel_network:
    driver: bridge
